### ISSUE TITLE
ERROR: Could not build wheels for pyzmq, which is required to install pyproject.toml-based projects

### ISSUE THREAD

**Issue by axiba053** [broadinstitute/CellBender#344]
Hello, I encountered the following error while installing Cellbender on a CentOS server with Python version 3.11. After successfully installing 'pyzmq' separately using 'pip install pyzmq', I still encountered the same error when installing Cellbender. 
How can I resolve this issue? Thank you!

```
pip install cellbender
................
Building wheel for pyzmq (pyproject.toml) ... error
  error: subprocess-exited-with-error
  
  × Building wheel for pyzmq (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [176 lines of output]
..................
error: command 'g++' failed: Permission denied
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for pyzmq
Successfully built cellbender
Failed to build pyzmq
ERROR: Could not build wheels for pyzmq, which is required to install pyproject.toml-based projects
```

**Comment by jlumpe** [comment]
Same here trying to run `pip install 'jupyterlab>=3,<4'`:

```
      In file included from /home/jared.lumpe/opt/mambaforge/envs/another-jupyter/include/python3.12/dictobject.h:90,
                       from /home/jared.lumpe/opt/mambaforge/envs/another-jupyter/include/python3.12/Python.h:64,
                       from zmq/backend/cython/_device.c:25:
      /home/jared.lumpe/opt/mambaforge/envs/another-jupyter/include/python3.12/cpython/dictobject.h:22:34: note: declared here
           Py_DEPRECATED(3.12) uint64_t ma_version_tag;
                                        ^~~~~~~~~~~~~~
      zmq/backend/cython/_device.c: In function ‘__Pyx_PyInt_As_int’:
      zmq/backend/cython/_device.c:5408:53: error: ‘PyLongObject’ {aka ‘struct _longobject’} has no member named ‘ob_digit’                                                                                                                                                                                                                                            const digit* digits = ((PyLongObject*)x)->ob_digit;
                                                           ^~
      zmq/backend/cython/_device.c:5463:53: error: ‘PyLongObject’ {aka ‘struct _longobject’} has no member named ‘ob_digit’                                                                                                                                                                                                                                            const digit* digits = ((PyLongObject*)x)->ob_digit;
                                                           ^~
      zmq/backend/cython/_device.c: In function ‘__Pyx_PyInt_As_long’:
      zmq/backend/cython/_device.c:5680:53: error: ‘PyLongObject’ {aka ‘struct _longobject’} has no member named ‘ob_digit’                                                                                                                                                                                                                                            const digit* digits = ((PyLongObject*)x)->ob_digit;
                                                           ^~
      zmq/backend/cython/_device.c:5735:53: error: ‘PyLongObject’ {aka ‘struct _longobject’} has no member named ‘ob_digit’                                                                                                                                                                                                                                            const digit* digits = ((PyLongObject*)x)->ob_digit;
                                                           ^~
      zmq/backend/cython/_device.c: In function ‘__Pyx_PyIndex_AsSsize_t’:
      zmq/backend/cython/_device.c:6086:45: error: ‘PyLongObject’ {aka ‘struct _longobject’} has no member named ‘ob_digit’                                                                                                                                                                                                                                    const digit* digits = ((PyLongObject*)b)->ob_digit;
                                                   ^~
      ************************************************
      ************************************************
      ************************************************
      error: command '/usr/bin/gcc' failed with exit code 1
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for pyzmq
Failed to build pyzmq
ERROR: Could not build wheels for pyzmq, which is required to install pyproject.toml-based projects
```

This is in a fresh Conda installation containing only Python 3.12.3:

```
$ pip list
Package    Version
---------- -------
pip        24.0
setuptools 69.5.1
wheel      0.43.0
```

**Comment by sjfleming** [comment]
Hi @axiba053 and @jlumpe 

Currently cellbender only works on python 3.7

This may be part of the problem!  I recommend installing in a miniconda setup with python 3.7.  See if that solves the issue.  Python 3.12 or 3.11 will cause problems for cellbender.

**Comment by jlumpe** [comment]
@sjfleming Actually I think I had a bunch of tabs open with search results for this issue and accidentally typed my comment in this issue instead of the one actually in the `pyzmq` repo, I wasn't even trying to use CellBender. I deleted my previous comment.
